# Generated by Django 2.2.16 on 2025-11-01 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='Ничего', max_length=500, verbose_name='О себе')),
                ('birth_date', models.DateField(default='2000-01-01', verbose_name='Дата рождения')),
                ('avatar', models.ImageField(default='images/default/defualt.jpg', upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(default='random_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
