# Generated by Django 2.2.16 on 2025-11-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/default/default.jpg', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
