# Generated by Django 2.2.16 on 2025-10-14 17:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('developer', models.CharField(max_length=64, verbose_name='Разработчик')),
                ('release_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2050)], verbose_name='Год выхода')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название ОС')),
                ('icon_class', models.CharField(max_length=64, verbose_name='Класс иконки')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(choices=[('I5_12400F', 'Intel core i5 12400F'), ('I3_13400KF', 'Intel Core i3 13400KF'), ('RYZEN5_3600', 'AMD Ryzen 5 3600')], default='I5_12400F', max_length=16, verbose_name='Процессор')),
                ('ram', models.CharField(choices=[('2', 2), ('4', 4), ('8', 8), ('16', 16), ('32', 32)], default='4', max_length=2, verbose_name='Кол-во оперативной памяти')),
                ('gpu', models.CharField(choices=[('NVIDIA_RTX4060', 'Nvidia Geforce RTX 4060'), ('NVIDIA_GTX1080TI', 'Nvidia GeForce GTX 1080 ti'), ('AMD_RX6600', 'AMD radeon RX 6600'), ('AMD_RX580', 'AMD radeon RX 580')], default='NVIDIA_RTX4060', max_length=24, verbose_name='Видеокарта')),
                ('os', models.CharField(choices=[('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11'), ('Ubuntu 20.04', 'Ubuntu 20.04'), ('macOS Monterey', 'macOS Monterey')], default='Windows 10', max_length=50, verbose_name='Операционная система')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_requirements', to='games.Game', verbose_name='Игра')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[['Completed', 'Завершено'], ['Canceled', 'Отменено'], ['Pending', 'Обрабатывается']], default='Pending', max_length=32, verbose_name='Статус заказа')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('games', models.ManyToManyField(to='games.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='games.Genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='games.OperationSystem', verbose_name='Поддерживаемые ОС'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(related_name='carts', to='games.Game', verbose_name='Игра')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pub_date',),
                'unique_together': {('user', 'game')},
            },
        ),
    ]
